language: php

php: [7.1, 7.2, 7.3, hhvm]

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.1
    - php: 7.2
  allow_failures:
    - php: 7.3
    - php: hhvm

install:
  - composer self-update
  - composer update
